---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(JuliaCall)

```

```{r}
exp_cdf <- function(x, lambda){
  1 - exp(-lambda * x)
}

# double check to make sure our reinvention is correct
exp_cdf(x=2, lambda=2)
pexp(q=2, rate=2)

# this is what the exponential cdf looks like
plot(seq(0,3,.1), exp_cdf(seq(0,3,.1), lambda=2))

# transform exponential cdf to make more numerically stable
exp_l_cdf <- function(x, lambda){
  log1p( - exp(-lambda * x))
}

# now integrate the density numerically
exp_l_cdf2 <- function(x1, lambda1) {
  
  # return the log cdf
  log(integrate(dexp, rate = lambda1, lower = 0, upper = x1)$value)
}

# now make function to simulate draws from exponential distribution
simtime <- function(par, method = "analytic"){
  # sample between 0 and 1
  usamp <- runif(n=1, 0, 1)
  
  # objective function
  if(method == "analytic") {
    x_obj_fun <- function(x, u=usamp, lambda=par){
      exp_l_cdf(x, lambda) - log(u)
    }
  } else {
    x_obj_fun <- function(x, u=usamp, lambda=par){
      exp_l_cdf2(x, lambda) - log(u)
    }
  }
  
  # SOLVE!
  uniroot(f=x_obj_fun, interval=c(0,10))$root
}


# sanity check
simulated_data <- replicate(10000, simtime(par=2, method = "numeric"))

hist(simulated_data, freq = FALSE, breaks=50)

lines(seq(0,4,0.01), dexp(seq(0,4,0.01), rate = 2), col="red")


# another sanity check
simulated_correct_data <- rexp(10000, rate=2)
hist(simulated_correct_data, freq = FALSE, breaks=seq(0,10,0.1), col="red", add=TRUE)
```

```{julia}

using Random, Distributions

function exp_cdf_J(x, lambda)
  y = 1 - exp(-lambda * x)
  return(y)
end
```

```{julia}
# double check to make sure our reinvention is correct
# scale(d)           # Get the scale parameter, i.e. θ (theta)
# rate(d)            # Get the rate parameter, i.e. 1 / θ
#in distributions package - Exponential takes the scale, so to be equivalent with base::pexp(rate) and our specifications use 1 / theta

exp_cdf_J(2, 2)
cdf(Exponential(2), 2) #scale
cdf(Exponential(1/2), 2) #rate
```
```{r}
#R and JUlia behaving the same
pexp(q=2, rate=2)
```

```{julia}
# this is what the exponential cdf looks like (in Julia)
using Plots
a = collect(0:.1:3)
d = []
for i in a
  push!(d, exp_cdf_J(i,2))
end

using Plots
plot(a,d, seriestype= :scatter, label = "Wheel ExpCDF")
plot!(a,cdf(Exponential(1/2), a), seriestype = :line, color = :green, label = "package ExpCDF")
```

```{r}
#numerically stable
# transform exponential cdf to make more numerically stable

a <- seq(0,3,.1)
l <- 2

exp_l_cdf <- function(x, lambda){
  log1p( - exp(-lambda * x))
}

exp_cdf <- function(x, lambda){
  1 - exp(-lambda * x)
}

exp(exp_l_cdf(a,l)) - exp_cdf(a,l)

```
```{julia}

#numerically stable Julia
#https://tamaspapp.eu/post/log1p/

function expCdf_Jstable(x, lambda)
  y = log1p(- exp(-lambda * x))
  return(y)
end

a = expCdf_Jstable(2,2)
exp(a)
exp_cdf_J(2,2)

```


```{r}
# now integrate the density numerically
expCdf_Rstable2 <- function(x1, lambda1) {
  
  # return the log cdf from the probability density function
  log(integrate(dexp, rate = lambda1, lower = 0, upper = x1)$value)
}

exp(expCdf_Rstable2(2,2))
pexp(2,2)
```

```{julia}
#Pkg.add("QuadGK")
using QuadGK
#equation for pdf returns the cdf
integral, err = quadgk(x -> (2*exp(-2 * x)), 0, 2)
cdf(Exponential(1/2), 2)

```

```{julia}
# in a formula
function logCDF_integral(x, lambda)
  integral, err = quadgk(x -> (lambda*exp(-lambda * x)), 0, 2)
  return(log(integral))
end

a=logCDF_integral(2,2)
exp(a)
```
```{julia}
#Pkg.add("Roots")
using Roots

f(x) = exp(x) - x^4
a=find_zero(f, (-10, 0))
f(a)
```


```{julia}

#making find_zero recognize lambda and u
#here's a similar suggestion from stack overflow:
#https://stackoverflow.com/questions/53824498/finding-univariate-roots-in-julia-of-a-function-with-many-arguments

function a_1(x)
  3 + x
end

find_zero(a_1, 1)

###this works nested
function a_2_root(y)
    function a_3(x)
        x + y
    end
    find_zero(a_3, 1)
end

a_2_root(10)

### this works using an anonymous function
function a_3_root(y)
    u = rand(1)
    a_3(x) = x + y + u[1]
    find_zero(a_3, 1)
end

a_3_root(1)
```


```{r}
exp_l_cdf <- function(x, lambda){
  log1p( - exp(-lambda * x))
}

# now integrate the density numerically
exp_l_cdf2 <- function(x1, lambda1) {
  
  # return the log cdf
  log(integrate(dexp, rate = lambda1, lower = 0, upper = x1)$value)
}
```

```{julia}
#posted example: https://discourse.julialang.org/t/solve-for-upper-lower-bound-of-a-numerical-definite-integral/58164/25

f1(x)=5(1-x)^4
f2(x)=quadgk(f1,0,x)[1]-0.9
find_zero(f2,0.5)
```

```{julia}
f4(x)= (2*exp(-2*x)) #pdf
f5(x)= log(quadgk(f4, 0, x)[1]) #cdf using integration
find_zero(f5,3)
```
```{julia}

a=log(quadgk(x -> lambda*exp(-lambda*x), 0, 1)[1]) -log(2)
typeof(a)
log

```


```{julia}
#QC check with seed for comparison between methods
#numerically is obv. not as stable without logs - this is a bug - at the moment add log and find_zero fails to converge because of NaN or in the search for integral method - need to read more in the documentation to overcome this - solution could be in 'quadgk' or 'root' or both....

function solver(method, lambda)
Random.seed!(1)
  u = rand(1)
    if method == "prepackaged"
      f1(x) = (log(cdf(Exponential(1/lambda),x))) - log(u[1])
      find_zero(f1,(0,10))
     elseif method == "analytic"
       f2(x) = (log1p(-exp(-lambda * x))) - log(u[1])
       find_zero(f2,(0,10))
     else
       f3(x)= (quadgk(x -> lambda*exp(-lambda*x), 0, x)[1]) - (u[1])
       find_zero(f3,(0,10))
      end
end

solver("prepackaged",3)
solver("analytic",3)
solver("numerically", 3)

```
```{julia}
#add replicate feature, for julia for loop is fast as vectorization
function JsimTime2(n, lambda)
simdata = []
for i = 1:n
  u = rand(1)
  f1(x) = (log(cdf(Exponential(1/lambda),x))) - log(u[1])
  y=find_zero(f1,(0,10))
  push!(simdata,y)
  end
  return(simdata)
end
```

```{julia}
#what package is this in? this is potential vectorized solution
#pmap(solver,1:10)
```


```{julia}
#for now for built function where n can be specified in the call
function JsimTime(n, lambda, method)
simdata = []
for i = 1:n
  u = rand(1)
    if method == "prepackaged"
      f1(x) = (log(cdf(Exponential(1/lambda),x))) - log(u[1])
      q=find_zero(f1,(0,10))
     elseif method == "analytic"
       f2(x) = (log1p(-exp(-lambda * x))) - log(u[1])
       q=find_zero(f2,(0,10))
     else
       f3(x)= (quadgk(x -> lambda*exp(-lambda*x), 0, x)[1]) - (u[1])
       q=find_zero(f3,(0,10))
      end
    push!(simdata,q)
    end
  return(simdata)
end
```

```{julia}
#sanity check julia
using Plots
Random.seed!(123)
simulated_data_P=JsimTime(1000,3, "prepackaged")
simulated_data_A=JsimTime(1000,3, "analytic")
simulated_data_N=JsimTime(1000,3, "numerically")
plot(simulated_data_P, seriestype = :histogram, color = :green,
     label = "P", linealpha = 0.3, fillalpha = 0.2)
plot!(simulated_data_A, seriestype= :histogram, color = :blue,
      label = "A", linealpha = 0.3, fillalpha = 0.2)
plot!(simulated_data_N, seriestype = :histogram, color = :red,
      label = "N", linealpha = 0.3, fillalpha = 0.2)
```



```{r}
# sanity check
set.seed(123)
simulated_data <- replicate(100, simtime(par=2, method = "numeric"))
hist(simulated_data, freq = FALSE, breaks=50)


lines(seq(0,4,0.01), dexp(seq(0,4,0.01), rate = 2), col="red")


# another sanity check
simulated_correct_data <- rexp(100, rate=2)
hist(simulated_correct_data, freq = FALSE, breaks=seq(0,10,0.1), col="red", add=TRUE)

```

